# Generated by Django 5.0.6 on 2024-07-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_join_request',
            field=models.BooleanField(default=False, verbose_name='가입신청'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_team_manager',
            field=models.BooleanField(default=False, verbose_name='팀장'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(default=None, max_length=50, verbose_name='팀'),
        ),
    ]
