# Generated by Django 5.0.6 on 2024-07-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_join_request_user_is_team_manager_user_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_join_request',
            field=models.BooleanField(default=False, null=True, verbose_name='가입신청'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_team_manager',
            field=models.BooleanField(default=False, null=True, verbose_name='팀장'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='팀'),
        ),
    ]
