# Generated by Django 5.0.6 on 2024-07-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_is_join_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_join_request',
        ),
        migrations.AddField(
            model_name='user',
            name='request_to',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='신청팀'),
        ),
    ]
