# Generated by Django 5.0.6 on 2024-07-04 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calenderdata',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_calendar.team'),
        ),
    ]
