# Generated by Django 5.0.6 on 2024-07-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_calendar', '0002_alter_calenderdata_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member1',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='member2',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='member3',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
