# Generated by Django 5.0.6 on 2024-07-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_calendar', '0005_remove_calenderdata_scheduled_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=50),
        ),
    ]
